services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_USER: auf
      MYSQL_PASSWORD: auf
      MYSQL_DATABASE: auf_website
      MYSQL_ROOT_PASSWORD: auf_root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - auf_mysqldata:/var/lib/mysql

volumes:
  auf_mysqldata:
